version: '0.1'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - BASE_URL=http://frontend:3000

networks:
  app-network:
    driver: bridge
