# Colorful-Xg Frontend Dockerfile

FROM node:18 AS build


WORKDIR /app


COPY package*.json ./

RUN npm install


COPY . .


RUN npm run build


FROM nginx:alpine

# Copy the built files from the previous step
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80 for the server
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
